# -*- coding: utf-8 -*-
"""covid-19_updator_using_python3.8.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lQZaI2cvc7h2hgT-E8Wsuq9j_zUmozDy
"""

import requests
import json
import time
from win10toast import ToastNotifier

def update():
  r = requests.get('https://coronavirus-19-api.herokuapp.com/all')
  data = r.json()
  text =  f'Confirmed Cases : {data["cases"]} \nDeaths : {data["deaths"]} \nRecovered : {["recovered"]}'

  while True:
    toast =  ToastNotifier()
    toast.show_toast("covid-19 update", text, duration = 20)
    time.sleep(60)

update()